### ISSUE TITLE
Play Store says incompatible with all my devices

### ISSUE THREAD

**Issue by dalewking** [danwallach/CalWatch#1]
A few months ago CalWatch stopped working and doesn't even show up as selectable. Play Store says it is incompatible with all my devices. My phone has Nougat and my watch is Android Wear 1.0 (Original Moto 360)

**Comment by danwallach** [comment]
I'm working on an Android Wear 2.0 version of CalWatch. Since this is a "spare time" activity of mine, it's taking a while. That won't help you, since Motorola isn't planning to release Wear 2.0 for the original Moto 360. Once I do get the Wear 2 thing working, I can try to work backwards and make a "multi-APK" version to support the old and new watches.

The reason, so far as I can tell, that CalWatch has been marked incompatible is that they've decided to nuke the original model wherein you installed an app once on your phone and it then had a "wear companion". 

I wish Google had managed the transition differently, but they didn't exactly ask for my opinion.

**Comment by danwallach** [comment]
FYI, I now have the very beginnings of an alpha of CalWatch running on Android Wear 2.0 (Moto 360v2). If you, or anybody else, is interested in being a private beta tester, please let me know.

**Comment by dalewking** [comment]
I have the original 360 so can't. And unfortunately my 360 has broken so that it is no longer wearable as a watch (band does not stay attached) so I no longer even use it

**Comment by danwallach** [comment]
Yeah, the 360v2 has external lugs, so much easier to attach different straps. Better battery life as well. Too bad they killed it.

**Comment by danwallach** [comment]
FYI, the new release should work just fine on Wear 1.x and 2.x, so I'm _finally_ closing this issue.

**Comment by dalewking** [comment]
Finally got it installed. Great to have CalWatch back. I bought a TicWatch E by the way to replace the Moto 360

**Comment by danwallach** [comment]
The fun part was realizing how much old code I didn't really need any more. For example, no need to read the step count and render it when I can just let the complication system do the work for users who want to know.

Anyway, feel free to write a review on the Play Store. That might help others to notice it.
